### ISSUE TITLE
How load new voices in the package ?

### ISSUE THREAD

**Issue by GuillermoParedes** [enricoaleandri/text-to-mp3#1]
Hello friend.

How load new voices in the package ? . I need the answer, please... (My english is basic)

**Comment by enricoaleandri** [comment]
Actually, you can not load different voice, because it use the google public API, so you can only use that tone of voice. Sorry for the late reply. 
If you need something else, just ask

**Comment by alassaneDiop** [comment]
Hello
I want the api return me the path of saving file, ho can i do ?
Excuse my english

**Comment by yongo1234** [comment]
Could @GuillermoParedes have meant how to change language at runtime?  I can change it in the package index.js, but I don't see how to do it in code.  For example, trying to change from english to spanish, I did this:
`txtomp3.attributes= {ie: "UTF-8",client : "tw-ob",tl : "es"}`
but it doesn't seem to have any effect.

**Comment by yongo1234** [comment]
Ok so it's been only a few minutes I'm sorry for necroing this thread, but 
`txttomp3.attributes.tl ="es";`
does.

**Comment by enricoaleandri** [comment]
#4 has been merged, and options object has been added to the signature to let user change language and other api attribute
