### ISSUE TITLE
Add config option

### ISSUE THREAD

**Issue by woudsma** [enricoaleandri/text-to-mp3#3]
Would it be an idea to add the option to supply a config object?
```ts
.saveMP3(text, filename, ?config)

// For example
.saveMP3('Test sentence', 'my-file', { tl: 'fr-FR' })
```
Like https://github.com/enricoaleandri/text-to-mp3/issues/1 I set the voice to English by editing `node_modules/text-to-mp3/index.js`:
```js
TextToMp3.prototype.attributes = {
  ie: 'UTF-8',
  client: 'tw-ob',
  tl: 'en-us'
};
```
Available languages: [Google Language Support](https://cloud.google.com/speech-to-text/docs/languages).

**Comment by enricoaleandri** [comment]
Thanks for your advice, it's a good idea, to let users customize API call. I will add configuration object asap.
